name: pokaml

windows:
  - main:
      layout: 3747,239x59,0,0{144x59,0,0,0,94x59,145,0[94x30,145,0,1,94x28,145,31,2]}
      panes:
        - cd ..
        - server:
          - cd ../server
          - ../dev-environment/setup
          - eval `opam config env`
          - ./watch
        - client:
          - cd ../client
          - npm install
          - eval `opam config env`
          - npm run prebuild && npm run build
